# Dependencies
plugins: [jekyll-paginate]
excerpt_separator: <!--more-->
categories: "finance|biblio|philosophy|programming|machine-learning"

# Permalinks
permalink:        /:year/:month/:day/:title/


# Setup
title:            Ruminator
tagline:          '^ to escape finding oneself in the ranks of the insane'
description:      '^ to escape finding oneself in the ranks of the insane'
url:               'https://pchaganti.github.io'
baseurl:          
imageurl:       '/assets/images/'

author:
  name:           'Prabhakar Chaganti'
  email:        'pchaganti@gmail.com'




# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pchaganti

social:
    twitter: https://twitter.com/pchaganti/

# Structure
paginate:         10

